hjs0913/SSU

- RealServer/Server/Npc.cpp
- RealServer/Server/Npc.h
- RealServer/Server/Player.cpp
- RealServer/Server/Player.h
- RealServer/Server/database.cpp
- RealServer/Server/fallen_flog.lua
- RealServer/Server/protocol.h
- RealServer/Server/send.cpp
- RealServer/Server/server.cpp
- SampleForServer/Network.cpp
> 서로간의 공격 설정

- RealServer/Server/Npc.cpp
- RealServer/Server/Npc.h
- RealServer/Server/protocol.h
- RealServer/Server/server.cpp
- SampleForServer/GameFramework.cpp
- SampleForServer/Network.cpp
- SampleForServer/Network.h
> 방향에 따른 움직임

- test/test/GameFramework.cpp
- test/test/Shader.cpp
> client error 수정

- RealServer/Server/Player.cpp
- RealServer/Server/Player.h
- RealServer/Server/fallen_chicken.lua
- RealServer/Server/fallen_flog.lua
- RealServer/Server/fallen_monkey.lua
- RealServer/Server/fallen_rabbit.lua
- RealServer/Server/fallen_tiger.lua
- RealServer/Server/protocol.h
- RealServer/Server/server.cpp
- RealServer/Server/wolf_boss.lua
- test_connect_server/test/GameFramework.cpp
- test_connect_server/test/Network.cpp
- test_connect_server/test/Network.h
> Position 처리 수정

- RealServer/Server/Npc.cpp
- RealServer/Server/Npc.h
- RealServer/Server/fallen_chicken.lua
- RealServer/Server/fallen_flog.lua
- RealServer/Server/fallen_monkey.lua
- RealServer/Server/fallen_rabbit.lua
- RealServer/Server/fallen_tiger.lua
- RealServer/Server/protocol.h
- RealServer/Server/server.cpp
- RealServer/Server/wolf_boss.lua
- test_connect_server/test/GameFramework.cpp
- test_connect_server/test/Network.cpp
- test_connect_server/test/Network.h
> 정의범 스킬 붙이기, A*알고리즘

- RealServer/Server/server.cpp
> NPC 이동성능 향상, NPC위치 조정

- RealServer/Server/fallen_chicken.lua
- RealServer/Server/fallen_flog.lua
- RealServer/Server/fallen_monkey.lua
- RealServer/Server/fallen_rabbit.lua
- RealServer/Server/fallen_tiger.lua
- RealServer/Server/wolf_boss.lua
- test_connect_server/test/GameFramework.cpp
- test_connect_server/test/Player.cpp
- test_connect_server/test/Shader.cpp
> 몬스터 공격 오류 수정, 몬스터와 장애물 높이값 적용

- RealServer/Server/protocol.h
- RealServer/Server/server.cpp
- test_connect_server/test/Network.cpp
- test_connect_server/test/Shader.cpp
> (의범) 스킬 범위 수정, (기윤) 장애물 오류 수정

- RealServer/Server/server.cpp
- test_connect_server/test/GameFramework.cpp
- test_connect_server/test/Network.cpp
- test_connect_server/test/Network.h
- test_connect_server/test/UILayer.cpp
- test_connect_server/test/UILayer.h
> UI 이름, 속성, 직업 구현

- RealServer/Server/Player.cpp
- RealServer/Server/Player.h
- RealServer/Server/fallen_chicken.lua
- RealServer/Server/fallen_flog.lua
- RealServer/Server/fallen_monkey.lua
- RealServer/Server/fallen_rabbit.lua
- RealServer/Server/fallen_tiger.lua
- RealServer/Server/protocol.h
- RealServer/Server/send.cpp
- RealServer/Server/send.h
- RealServer/Server/server.cpp
- RealServer/Server/wolf_boss.lua
- test_connect_server/test/GameFramework.cpp
- test_connect_server/test/GameFramework.h
- test_connect_server/test/Network.cpp
- test_connect_server/test/Network.h
- test_connect_server/test/Object.cpp
- test_connect_server/test/Player.cpp
- test_connect_server/test/Shader.cpp
- test_connect_server/test/test1.cpp
> hp 연동, ui추가

- test_connect_server/test/GameFramework.cpp
- test_connect_server/test/Network.cpp
- test_connect_server/test/Object.cpp
- test_connect_server/test/UILayer.cpp
- test_connect_server/test/UILayer.h
> buff UI 타이머

- RealServer/Server/server.cpp
- test_connect_server/test/Network.cpp
> Merge오류 수정

- RealServer/Server/Gaia.cpp
- RealServer/Server/Partner.cpp
- RealServer/Server/protocol.h
- RealServer/Server/send.cpp
- RealServer/Server/send.h
- RealServer/Server/server.cpp
- test_connect_server/test/GameFramework.cpp
- test_connect_server/test/Network.cpp
- test_connect_server/test/Network.h
> 포트포워딩 에러 수정1

- RealServer/Server/protocol.h
- RealServer/Server/send.cpp
- RealServer/Server/send.h
- RealServer/Server/server.cpp
- SSUClient/GameFramework.cpp
- SSUClient/GameFramework.h
- SSUClient/Network.cpp
- SSUClient/Network.h
- SSUClient/Object.cpp
- SSUClient/Object.h
- SSUClient/PartyUI.cpp
- SSUClient/PartyUI.h
- SSUClient/Player.cpp
- SSUClient/Player.h
- SSUClient/SSUClient.cpp
- SSUClient/SSUClient.vcxproj
- SSUClient/SSUClient.vcxproj.filters
- SSUClient/Scene.cpp
- SSUClient/UILayer.cpp
- SSUClient/UILayer.h
> 모델 클라이언트 동기화

- SSUClient/GameFramework.cpp
- SSUClient/SSUClient.cpp
> 마우스 처리 및 중간발표

- RealServer/Server/protocol.h
- RealServer/Server/server.cpp
- SSUClient/GameFramework.cpp
- SSUClient/Network.cpp
- SSUClient/Network.h
- SSUClient/Player.cpp
- SSUClient/Player.h
- SSUClient/SSUClient.cpp
- SSUClient/Scene.cpp
- SSUClient/Scene.h
> 알맞는 모델 렌더링 Update

- RealServer/Server/Npc.cpp
- RealServer/Server/Partner.cpp
- RealServer/Server/protocol.h
- RealServer/Server/send.cpp
- RealServer/Server/send.h
- RealServer/Server/server.cpp
- SSUClient/GameFramework.cpp
- SSUClient/Network.cpp
- SSUClient/Player.cpp
- SSUClient/Player.h
- SSUClient/Scene.cpp
skill animation syncornize and error recurit
> skill animation syncornize and error recurit

- RealServer/Server/Partner.cpp
- RealServer/Server/database.cpp
- RealServer/Server/server.cpp
> 쿨타임 수정 , 오류 수정

- SSUClient/Network.cpp
- SSUServer/SSUServer/PacketManager.cpp
- SSUServer/SSUServer/Player.cpp
- SSUServer/SSUServer/Player.h
- SSUServer/SSUServer/database.cpp
- SSUServer/SSUServer/database.h
> 의범이 코드 붙이기 및 오류 수정

- SSUClient/Network.cpp
- SSUServer/SSUServer/ObjectManager.cpp
> 사망시 서버 오류 수정

- SSUClient/Network.cpp
- SSUClient/Object.cpp
- SSUClient/Object.h
- SSUClient/Player.cpp
- SSUClient/SSUClient.cpp
- SSUClient/Scene.cpp
> 애니메이션 버그 수정

- SSUClient/Network.cpp
- SSUClient/Player.cpp
- SSUClient/Scene.cpp
- SSUServer/SSUServer/PacketManager.cpp
레이드 Move에러 수정, 플레이어_레이드_애니메이션버그수정
> 레이드 Move에러 수정, 플레이어_레이드_애니메이션버그수정

- SSUClient/Object.cpp
- SSUClient/Scene.cpp
- SSUServer/SSUServer/ObjectManager.cpp
- SSUServer/SSUServer/Player.cpp
> 오류 수정 및 충돌처리

- SSUClient/TownNpc.cpp
- SSUServer/SSUServer/SectorManager.cpp
> Sector코드 수정, NPC Look수정

- SSUServer/SSUServer/Npc.cpp
- SSUServer/SSUServer/SectorManager.cpp
> NPC 이동 충돌처리

- SSUServer/SSUServer/Npc.cpp
- SSUServer/SSUServer/fallen_chicken.lua
- SSUServer/SSUServer/fallen_flog.lua
- SSUServer/SSUServer/fallen_monkey.lua
- SSUServer/SSUServer/fallen_rabbit.lua
- SSUServer/SSUServer/fallen_tiger.lua
- SSUServer/SSUServer/wolf_boss.lua
> NPC이동공격 자연스럽게

- SSUClient/GameFramework.cpp
- SSUClient/GameFramework.h
- SSUClient/Scene.cpp
- SSUServer/SSUServer/PacketManager.cpp
- SSUServer/SSUServer/TimerManager.cpp
> 마법사, 서포터 각 스킬 쿨타임 공유 없앰
